language: ruby
rvm:
- 2.3.4
cache: bundler
deploy:
  provider: rubygems
  api_key:
    secure: hBvJmGAW7EyztpN/eqqaL+cVZaTrKKvnZpjr9psR/QuQXPT/ytVvpHMcc/AGvRTv3w41GurF/yrl36O/F2VctEb0nVxVw16RZMrbA2Ax8bkeJgK730icSRLfohB6/4KZPQSq6MR1MrLby4YzOqSw3SENZiETSOgpdrH9dz+3ycz/bn7YGXU8tkGUpewNfACX3ojmI9WiRwAvBL2qjjbx2cVunUeB1u6E7RCV4ZiO1Z1frPzDdl/NvA0Ia0a38oqOtkQPr80ApkvjWTRnoR6ctfgQKAxPigleqn2/mwhUtLjjEU03SGy9cwE/5ATgRudS0BU1j2B+wofX+kTsIM582x/RTCMxIQHHbJ0zRk0GpKxQ28SbqgyFoDCQba+Z4H1kvVIAKf5khs9efmzWDwLZ5tBzLXgp3Y4qW0VbOJMy9oNWgGH7TJ+cEaGy83iTStQHjQs5Ey85jMDF/T5+alrJT/w6AZMJO6wOEqlaJkBD8ORbw5H1gDFPefVQclz/Dt/G9yoiuRMaGCVnKrtlah9p/+DJz6X4l6NFSVxeDkalk55kpL4Kc/j+5z0KudhpZ81RmcJnmZdq1nK7YYfpRnQtFy1Arsmh6ZypEZeDukfLFgS2vjRGlJlj63Iikrl6m7G+b1h0o3ca2x8mtTdUpRDnA8trTO+uUxi5iQAda+ZvSes=
  gem: guid_spanner
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.3.4"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: Rp2hkwHkNj2XRZMIYmOURJg2kGIVHxUqi1E8bLWaLF2pSPYXJ5UVMWAF9eoygUiJfh3Zy0vpGvkS2Uvh4CCL4rhWGqJ7sgCtq87q3ia589wvAePPrY8XrBsw2ZxCT+z+1E1YUZhojXZsl7YMIimLImgfz2yzrufddqUu5G2qhnHEEmJ7wpUs8M5hDwgNeBHrgY+YpPblg1O6I6m4eW3za/f4g/eAXuZcVQDtj9KGNkxOy5dxwZ3kcglXUu8U4Nf4osgJLAsUPgokeWxNHqS2PfUkR93lgK+wNHd4pNkVwq8Bh38moPYbsC+ZEh8wcGDRzPZUJNMYKCDVk/7haguV/KrF43xlczPhsT/iybBoiu4zwx3GsTS0xM/YgTfCxKA0f1kAM/CP+X56ccK0UMZ7BdAOa3PKhBVksK6ulL6WtajRL+wApl8RMCys31P4SUOS3amzT2ynWYv3JFWtp+0U8ZRoedeUMXbR+B403VrOQkAOUrO7omzztXyDNlsXey56w3E9EkTzwacXcaLhiBRBdz4Z7eaX9rfwGMLrQsWspNubqHsQjJkzEgi6kBbOXKR28Kq9rH6gzHzkVfHAzThWF9Jv8e6Lgfu+y0zoQXVRAY58wk8TIK6duzszHOEmkIy+3PumBhqurkYxOzjMz/5SkfK2o5d8ZZcPWoA0E1lYnnA=
